FROM apache/superset:latest

USER root
RUN /app/.venv/bin/python -m pip install --no-cache-dir --upgrade pip setuptools wheel \
 && /app/.venv/bin/python -m pip install --no-cache-dir pymysql

USER superset